{% set name = "prompt-toolkit" %}
{% set version = "3.0.53" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 9ec8a0ad96d5c56148b3f914aa79c1564c3fde5d2e6b876e7bc327e353cf8fa6

build:
  number: 0
  skip: true  # [py<310]

outputs:
  - name: {{ name }}
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python
        - pip
        - setuptools >=68
        - wheel
      run:
        - python
        - wcwidth >=0.1.4
      run_constrained:
        - prompt_toolkit {{ version }}

    test:
      source_files:
        - tests
      imports:
        - prompt_toolkit
        - prompt_toolkit.application
        - prompt_toolkit.clipboard
        - prompt_toolkit.completion
        - prompt_toolkit.contrib
        - prompt_toolkit.contrib.completers
        - prompt_toolkit.contrib.regular_languages
        - prompt_toolkit.eventloop
        - prompt_toolkit.filters
        - prompt_toolkit.formatted_text
        - prompt_toolkit.input
        - prompt_toolkit.key_binding
        - prompt_toolkit.key_binding.bindings
        - prompt_toolkit.layout
        - prompt_toolkit.lexers
        - prompt_toolkit.shortcuts
        - prompt_toolkit.styles
        - prompt_toolkit.widgets
      commands:
        - pip check
        - pytest -vv tests
      requires:
        - pip
        - pytest

  - name: prompt_toolkit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('prompt-toolkit', max_pin="x.x.x") }}

    test:
      imports:
        - prompt_toolkit
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/prompt-toolkit/python-prompt-toolkit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Library for building powerful interactive command lines in Python
  description: |
    prompt_toolkit is a library for building powerful interactive command
    lines and terminal applications in Python. It can be a pure Python
    replacement for GNU readline, but it can be much more than that.
  doc_url: https://python-prompt-toolkit.readthedocs.io
  dev_url: https://github.com/prompt-toolkit/python-prompt-toolkit

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - scopatz
    - asmeurer
  skip-lints:
    # doc_url is redirecting
    - reachable_url