{% set name = "prompt-toolkit" %}
{% set version = "3.0.52" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/prompt_toolkit/prompt_toolkit-{{ version }}.tar.gz
  sha256: 28cde192929c8e7321de85de1ddbe736f1375148b02f2e17edd840042b1be855

build:
  number: 0
  skip: true  # [py<38]

outputs:
  - name: prompt-toolkit
    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]
    requirements:
      host:
        - python
        - pip
        - setuptools
        - wheel
      run:
        - python
        - wcwidth
      run_constrained:
        - prompt_toolkit {{ version }}
    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - prompt_toolkit
        - prompt_toolkit.application
        - prompt_toolkit.clipboard
        - prompt_toolkit.completion
        - prompt_toolkit.contrib
        - prompt_toolkit.contrib.completers
        - prompt_toolkit.contrib.regular_languages
        - prompt_toolkit.eventloop
        - prompt_toolkit.filters
        - prompt_toolkit.formatted_text
        - prompt_toolkit.input
        - prompt_toolkit.key_binding
        - prompt_toolkit.key_binding.bindings
        - prompt_toolkit.layout
        - prompt_toolkit.lexers
        - prompt_toolkit.outputs
        - prompt_toolkit.shortcuts
        - prompt_toolkit.styles
        - prompt_toolkit.widgets

  - name: prompt_toolkit
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('prompt-toolkit', max_pin="x.x.x") }}
    test:
      imports:
        - prompt_toolkit

about:
  home: https://github.com/prompt-toolkit/python-prompt-toolkit
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Library for building powerful interactive command lines in Python
  description: |
    prompt_toolkit is a library for building powerful interactive command
    lines and terminal applications in Python. It can be a pure Python
    replacement for GNU readline, but it can be much more than that.
  doc_url: https://python-prompt-toolkit.readthedocs.io
  dev_url: https://github.com/prompt-toolkit/python-prompt-toolkit

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - scopatz
    - asmeurer
