{% set name = "prompt_toolkit" %}
{% set version = "1.0.9" %}
{% set sha256 = "cd6523b36adc174cc10d54b1193eb626b4268609ff6ea92c15bcf1996609599c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pygments
    - six >=1.9.0
    - wcwidth

test:
  imports:
    - prompt_toolkit
    - prompt_toolkit.clipboard
    - prompt_toolkit.contrib
    - prompt_toolkit.contrib.completers
    - prompt_toolkit.contrib.regular_languages
    - prompt_toolkit.contrib.telnet  # [not win]
    - prompt_toolkit.contrib.validators
    - prompt_toolkit.eventloop
    - prompt_toolkit.filters
    - prompt_toolkit.key_binding
    - prompt_toolkit.key_binding.bindings
    - prompt_toolkit.layout
    - prompt_toolkit.terminal

about:
  home: https://github.com/jonathanslenders/python-prompt-toolkit
  license: BSD 3-clause
  license_file: LICENSE
  summary: Library for building powerful interactive command lines in Python
  description: |
    prompt_toolkit is a library for building powerful interactive command 
    lines and terminal applications in Python. It can be a pure Python 
    replacement for GNU readline, but it can be much more than that.
  doc_url: http://python-prompt-toolkit.readthedocs.io
  dev_url: https://github.com/jonathanslenders/python-prompt-toolkit

extra:
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - scopatz
