{% set version = "0.60" %}

package:
    name: prompt_toolkit
    version: "{{ version }}"

source:
    fn: prompt_toolkit-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/p/prompt_toolkit/prompt_toolkit-{{ version }}.tar.gz
    md5: 516826aff6a09536037b6d02a9a3451d

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pygments
        - six >=1.9.0
        - wcwidth

test:
    imports:
        - prompt_toolkit
        - prompt_toolkit.clipboard
        - prompt_toolkit.contrib
        - prompt_toolkit.contrib.completers
        - prompt_toolkit.contrib.regular_languages
        - prompt_toolkit.contrib.telnet  # [not win]
        - prompt_toolkit.contrib.validators
        - prompt_toolkit.eventloop
        - prompt_toolkit.filters
        - prompt_toolkit.key_binding
        - prompt_toolkit.key_binding.bindings
        - prompt_toolkit.layout
        - prompt_toolkit.terminal

about:
    home: https://github.com/jonathanslenders/python-prompt-toolkit
    license: LICENSE.txt
    summary: 'Library for building powerful interactive command lines in Python'

extra:
    recipe-maintainers:
        - ocefpaf
        - scopatz
