{% set version = "1.0.3" %}

package:
    name: prompt_toolkit
    version: "{{ version }}"

source:
    fn: python-prompt-toolkit-aa476e255be606edbf2287bfa978fe6aad2e9daa.tar.gz
    url: https://github.com/jonathanslenders/python-prompt-toolkit/archive/aa476e255be606edbf2287bfa978fe6aad2e9daa.tar.gz
    sha1: 212559aa239d8a3ae2cfc06e7f26bb49e8e9ad3f

build:
    script: python setup.py install --single-version-externally-managed --record=record.txt
    number: 0

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - pygments
        - six >=1.9.0
        - wcwidth

test:
    imports:
        - prompt_toolkit
        - prompt_toolkit.clipboard
        - prompt_toolkit.contrib
        - prompt_toolkit.contrib.completers
        - prompt_toolkit.contrib.regular_languages
        - prompt_toolkit.contrib.telnet  # [not win]
        - prompt_toolkit.contrib.validators
        - prompt_toolkit.eventloop
        - prompt_toolkit.filters
        - prompt_toolkit.key_binding
        - prompt_toolkit.key_binding.bindings
        - prompt_toolkit.layout
        - prompt_toolkit.terminal

about:
    home: https://github.com/jonathanslenders/python-prompt-toolkit
    license: BSD 3-clause
    summary: Library for building powerful interactive command lines in Python

extra:
    recipe-maintainers:
        - ocefpaf
        - scopatz
