travis:
  secure:
    BINSTAR_TOKEN: GXT7Yqb+KD/Jj3EoFUf2JVcyyIZJW7I+uHYuZQc7OW/vnwx8ETSFt7L6JAikEkBcjNDE6Ho8SNqbu4vrKjpxuzpe36u5VXUCUVKmUcBA4O1E8T7KrbsYI/e97Top5R/6Jb3SpJcRpVcF/yh96bfSQ/wLQF3ZTBs/tslnZAhaD2NifGs3VcAl0Y66Mbkze1dufbK0ca8g6T9VcKPygvc7W3wmYrRbmsQRBfJTbPcVK2sebrqL+ItzDiFq+Zm2BvmTGaT7vm29OuQgncpjjPpffuDhl3dU1UeOd6zyBjxXxAbrVqGFdXefUWCMeUVb/qrc6QaBM5IpXExH51q/ygNF/cdeQT6Wg1+3AyWTV8u0/TQvgPtyOokcWRc9+CUnR4liW2uo/rV9aQO96KXMTZNaGnLmkaJFnn893NLS0gB46fvB9pXcEL0R4E9e02vgVeEdC6Ay3UpPXTzK99srouih71d6MTChtGfuYk9+yt53m+apAwqC+yUxaEqONDOEZQO+YpwqyJmZcvbK+Zq4zDru8oo2LegtJyJ4MjgUdkd8yTmT1IXuOgS2cpeBX50TGRT3Ai3qRJwDlxCH3iIPCqCceugNHdysUoDDI7hr9DKK5JbTa8vjtuNea8eTBqiWp2tXxFnT7ALC4sJp6Ww2hkdRhaX8QAhPCM5neeD3/eT86CA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
